export default {
    "GET_COUNTRIES" : "SELECT * FROM COUNTRIES",
    "GET_COUNTRY" : "SELECT * FROM COUNTRIES WHERE COUNTRY_ID = ",
    "GET_EMPLOYEES" : "SELECT * FROM EMPLOYEES",
    "GET_EMPLOYEE" : "SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID = ",
    "GET_DEPARTMENTS" : "SELECT * FROM DEPARTMENTS",
    "GET_DEPARTMENT" : "SELECT * FROM DEPARTMENTS WHERE DEPARTMENT_ID = ",
    "GET_JOBS" : "SELECT * FROM JOBS",
    "GET_LOCATIONS" : "SELECT * FROM LOCATIONS",
    "GET_REGIONS" : "SELECT * FROM REGIONS",
    "GET_LAST_REGION_ID" : "SELECT REGION_ID FROM REGIONS WHERE REGION_ID=(SELECT MAX(REGION_ID) FROM REGIONS)",
    "INSERT_NEW_REGION" : "INSERT INTO REGIONS(REGION_ID,REGION_NAME) VALUES(%d, '%s')",
    "REMOVE_REGION" : "DELETE FROM REGIONS WHERE REGION_ID = %d",
    "UPDATE_REGION" : "UPDATE REGIONS SET REGION_NAME = %s WHERE REGION_ID = %d"

}